language: python
python:
  - "2.7"
  - "3.5"

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database dj_pq_test;' -U postgres

env:
  - DATABASE_URL=postgres://localhost/dj_pq

install: "python setup.py install && pip install psycopg2 dj_database_url"
script: "django-admin.py test --settings=dj_pq.tests.settings --pythonpath=."
